### ISSUE TITLE
Meaningful failure message for jakarta transformation

### ISSUE THREAD

**Issue by KyleAure** [eclipse/transformer#101]
I saw some TODOs in the code but did not see any issues addressing them.
When the Jakarta transformer fails, a result code is returned, but there is no meaningful message output in the case of a failure. 

https://github.com/eclipse/transformer/blob/4a34b350fe73da376806d25f136a869c363cb6c7/org.eclipse.transformer.cli/src/main/java/org/eclipse/transformer/jakarta/JakartaTransformer.java#L29-L31

Additionally, the result codes are constants instead of an enum which would make analyzing the results codes easier. 

https://github.com/eclipse/transformer/blob/4a34b350fe73da376806d25f136a869c363cb6c7/org.eclipse.transformer/src/main/java/org/eclipse/transformer/Transformer.java#L69-L80

**Comment by tbitonti** [comment]
Here are updated messages.  Note the addition

**Transformer Return Code [ 0 ] [ Success ]**

```
[main] INFO org.eclipse.transformer.maven.TransformMojo - Text files will be updated
[main] INFO org.eclipse.transformer.maven.TransformMojo - Java direct string updates will be performed
[main] INFO org.eclipse.transformer.maven.TransformMojo - All resources will be selected
[main] INFO org.eclipse.transformer.maven.TransformMojo - Action selected for input [ C:/Users/THOMAS~1/AppData/Local/Temp/service155470455783007123.war ]: WAR Action
[main] INFO org.eclipse.transformer.maven.TransformMojo - Input  [ C:/Users/THOMAS~1/AppData/Local/Temp/service155470455783007123.war ] as [ C:\Users\THOMAS~1\AppData\Local\Temp\service155470455783007123.war ]
[main] INFO org.eclipse.transformer.maven.TransformMojo - Output [ C:/dev/jakarta-repo-pub/transformer/maven-plugins/transformer-maven-plugin/target/simple-service-test3-transformed-1.0-SNAPSHOT.zip ] as [ C:\dev\jakarta-repo-pub\transformer\maven-plugins\transformer-maven-plugin\target\simple-service-test3-transformed-1.0-SNAPSHOT.zip ]
[main] INFO org.eclipse.transformer.maven.TransformMojo - [  All Resources ] [      7 ] Unaccepted [      0 ]   Accepted [      7 ]
[main] INFO org.eclipse.transformer.maven.TransformMojo - [  All Unchanged ] [      6 ]     Failed [      0 ] Duplicated [      0 ]
[main] INFO org.eclipse.transformer.maven.TransformMojo - [    All Changed ] [      1 ]    Renamed [      0 ]    Content [      1 ]
[main] INFO org.eclipse.transformer.maven.TransformMojo - Transformer Return Code [ 0 ] [ Success ]
```

**Comment by KyleAure** [comment]
@tbitonti Thanks for the update!  This looks great.  I'd be okay with this issue being closed.  But can wait until after the EE10 issue is closed if that is the process y'all like to follow.

**Comment by tbitonti** [comment]
This will be updated by the PR for issue #186.
