### ISSUE TITLE
Run the transformer all in memory

### ISSUE THREAD

**Issue by Thihup** [eclipse/transformer#125]
Today the Transfomer allows us to use the command line to specify the options.
However, it also makes the transformer filesystem dependent. I have a use case where I'd like to run the transformer all in memory using the [Jimfs](https://github.com/google/jimfs).

Allowing the transformer to run all in memory is something that could be allowed or there are other reasons why the filesystem approach was used? 

I guess making the project filesystem dependent also makes it hard to run the project as a Java agent.

**Comment by tbitonti** [comment]
Hi.  There are two layers of function within the transformer: One is transforming individual resources.  Two is transforming aggregates, such as JavaEE application archives.

**Comment by tbitonti** [comment]
What is missing is the ability to select a transform action for a stream based resource.  That capability is currently buried in container actions, and at the Transformer root.  See Transformer.TransformerOptions.acceptAction:

```
		public boolean acceptAction() {
			String actionName = getOptionValue(AppOption.FILE_TYPE);
			if (actionName != null) {
				for (ActionImpl action : getRootAction().getActions()) {
					if (action.getActionType()
						.matches(actionName)) {
						dual_info("Forced action [ %s ] [ %s ]", actionName, action.getName());
						acceptedAction = action;
						return true;
					}
				}
				dual_error("No match for forced action [ %s ]", actionName);
				return false;

			} else {
				acceptedAction = getRootAction().acceptAction(inputName, inputFile);
				if (acceptedAction == null) {
					dual_error("No action selected for input [ %s ]", inputName);
					return false;
				} else {
					dual_info("Action selected for input [ %s ]: %s", inputName, acceptedAction.getName());
					return true;
				}
			}
		}
```

**Comment by bjhargrave** [comment]
I think the current code base can be used for all-in-memory transformations. Please open an issue with specific requested changes that might be necessary for your use case.
