### ISSUE TITLE
Use property instead of classifier to define an alternative artifactId for the transformed archive

### ISSUE THREAD

**Issue by gitmotte** [eclipse/transformer#133]
Do not use the classifier, but add a property artifactId to define an alternative artifactId for the transformed jar/war/...

**Example with artifactId Property**
```
<plugin>
        <groupId>org.eclipse.transformer</groupId>
        <artifactId>org.eclipse.transformer.maven</artifactId>
        <version>0.2.0</version>
        <executions>
          <execution>
            <id>jakarta-ee</id>
            <goals>
              <goal>run</goal>
            </goals>
            <phase>package</phase>
            <configuration>
              <artifactId>${project.artifactId}-jakarta</artifactId>
            </configuration>
          </execution>
        </executions>
</plugin>
```

Otherwise the known classifiers **test/sources/javadoc**... will be superseded by the given classifier and naming of test/sources will not work correctly - see https://github.com/eclipse/transformer/issues/131

**Comment by bjhargrave** [comment]
Artifacts produced by a project should match the project's maven coordinates. The new `jar` goal can be used another project with the desired maven coordinates to transform an artifact.
