### ISSUE TITLE
Allow the Transformer to be used as a Java Agent

### ISSUE THREAD

**Issue by aseovic** [eclipse/transformer#136]
It looks like the current plan is to support build-time transformation via CLI and Maven/Gradle plugins, or runtime transformation via direct API usage within custom class loaders.

It seems like the latter would be better served by a Java Agent and a `ClassFileTransformer` which would be independent of the class loader used and wouldn't require custom class loader implementation solely for this purpose.

Happy to contribute the implementation, just wanted to check first to see if this option was already considered and rejected for some reason.

**Comment by tbitonti** [comment]
Hi.  That was considered, and is still a possibility.  For performance and simplicity, build time transformation was selected as the initial function.  However, the transformer was built with the idea of dynamic transformation as one of the desired functions.

There is  a start, here:

https://github.com/eclipse/transformer/blob/main/org.eclipse.transformer.cli/src/test/java/transformer/test/TransformClassLoader.java

There may be problems using a java agent, per se, depending on where the agent runs during normal class loading.  Performing the transformation at the resource level ensures that all consumers see the updated class bytes.  Performing the transformation only when defining a class means that the class resource will be unchanged, which is a problem for any APIs (e.g., ASM) which look at the raw class resource.

**Comment by bjhargrave** [comment]
With the recent refactorings, it is much easier to implement a Java Agent driver for transformer. If you would be interested in providing a Java Agent implementation, please open a PR. Thanks.
