### ISSUE TITLE
Allow the transformed artifact to have it's own maven ID and runtime dependencies

### ISSUE THREAD

**Issue by tevans78** [eclipse/transformer#139]
If we have artifactA-1.0.jar which depends on artifactB-1.0.jar and transform them both then I get artifactA-1.0-transformed.jar and artifactB-1.0-transformed.jar. Great … but artifactA-1.0-transformed.jar still has a dependency on artifactB-1.0.jar. If the project that uses them declares a dependency on the two artifacts with the “transformed” classifier, it actually ends up pulling in both versions of artifactB.

This would be much clearer if the transformer operated in it's own maven project, with it's own artifact ID.
If the transformed artifact is completely separated from the original then it can also have a customized set of runtime dependencies.

At compile/package time...
artifactA-transformed-1.0 will depend on artifactA-1.0, which has a transitive dependency on artifactB-1.0.
artifactB-transformed-1.0 will depend on artifactB-1.0

At runtime, the dependencies will simply be...
artifactA-transformed-1.0 depends on artifactB-transformed-1.0

I have a working prototype that I will create a PR from.
I also note that there are some similar issues already open:
https://github.com/eclipse/transformer/issues/137 (@frantuma)
https://github.com/eclipse/transformer/issues/133 (@gitmotte)

**Comment by tevans78** [comment]
I have attached a draft PR for discussion. Unfortunately I am on vacation next week and I won't be able to further update it until the week after.

**Comment by c-koell** [comment]
We have the same problem. Are there any workarounds ?

**Comment by tevans78** [comment]
I think this issue has been resolved by allowing the transformer to run as a bnd plugin but I don't know which PR added that functionality. @bjhargrave can you answer this ... and then we should close this issue off properly?

**Comment by tevans78** [comment]
I am assuming that bnd functionality can be used from maven just as Open Liberty does using gradle.

**Comment by bjhargrave** [comment]
> I am assuming that bnd functionality can be used from maven just as Open Liberty does using gradle.

Maven builds are different than the Bnd Workspace model build used by Open Liberty. So one can use the Bnd plugin in a maven build when making an artifact, there is still the need for transforming existing binaries.

My current thinking is that the transformer maven plugin needs to change to, instead of compiling source code and packaging into an artifact(jar), take an input artifact and generate the project's output artifact by transforming the input artifact. So the project can then define the output artifact's desired GAV and dependencies like any other maven project. Maven projects can be then put in a "pipeline" where one project is "normal" and compiles and packages code into an artifact and another project can transform the artifact of the first projects into a different artifact with different GAV and dependencies.

**Comment by c-koell** [comment]
I think its a common problem. As @tevans78 explained it we have the same situation.
We have more artifacts with transitive dependencies like following example

basic_artifact (no dependencies)
basic_jsf_artifact -> basic_artifact
basic_app_artifact -> basic_jsf_artifact -> basic_artifact

So we have to create from each artifact a jakarta version.

Normally we add the basic_app_artifact dependency to one of our applications and get the other artifacts as transitive dependencies.
If me migrate one application to jakarta namespace (EE9.1) we must now add each artifact dependency seperatly and must also exclude the non jakarta dependencies.

From the application view we must define following dependencies with its exclusions.

basic_artifact-jakarta
basic_jsf_artifact-jakarta -> exclude[basic_artifact]
basic_app_artifact-jakarta -> exclude[basic_jsf_artifact,basic_artifact]

One option is to define the transitive dependencies in the basic_app_artifact/basic_jsf_artifact as optional. This will work but we lost the transitive dependency feature.

Is there a good documentation how other will address this issue ?

**Comment by bjhargrave** [comment]
A new `jar` goal is added which will transform an artifact and use the project's maven metadata for the generated artifact. A classifier can also be specified.

**Comment by c-koell** [comment]
Hi @bjhargrave!

Is it possible to handle our problem with the new maven-plugin https://github.com/eclipse/transformer/issues/139#issuecomment-1118351587 ? I have taken a look at the new goals but i'm not sure how we can handle our problem exactly.

**Comment by c-koell** [comment]
@bjhargrave thanks for your explanation !

Is there a estimate date for a 0.5.0 release ?

**Comment by bjhargrave** [comment]
> Is there a estimate date for a 0.5.0 release ?

I am hoping in the next few weeks. Just working through the release of Bnd 6.3.0 which is a prereq for the Transformer 0.5.0 release.
