### ISSUE TITLE
Reduce Debug Output

### ISSUE THREAD

**Issue by dblevins** [eclipse/transformer#142]
There's a bit of a punishment for using the transformer plugin in a maven project, you can no longer use `mvn -X` to debug your maven setup.  The amount of debug information that the transformer prints is so large and takes so long that it's just not usable on anything but a tiny project.

Most ideal setup is by default the debug information is still pretty brief -- slightly more than the info level.  In this level we're not printing any formatted binary data to the console.  For the rare developer that wants that information (I suspect only ourselves), we have a configuration flag that can turn on various advanced debug output.

**Comment by tbitonti** [comment]
There are several small adjustments being made under issue #158.  Can you run with those changes and let us know if more adjustments are necessary?
