### ISSUE TITLE
Remove Packages From Manifest.MF

### ISSUE THREAD

**Issue by volosied** [eclipse/transformer#145]
Scenario:

In some rare scenarios, a new EE9 Bundle may have some packages removed when compared to the EE8 one.  The EE8 implementation bundle imports this particular package.    In the transformed EE9 Implementation, it also still imports now-transformed package. However, this may cause resolution failures as the import cannot be found as it was removed. 

For instance, 
An EE8 IMPL imports package javax.x.y.z from Bundle A. 

The transformed EE8 IMPL  still imports this transformed package. However, this transformed bundle now relies on Bundle B.  And Bundle B doesn't export the equivalent package (i.e. jakarta.x.y.z).  

In some sense, it's related to issue  #9.  

I'm currently working on a PR to address this scenario by specifying rules to remove these pruned packages from the manifest.

 Perhaps, something along the lines of 
`com.package.to.remove=<remove> `

The right hand side could be left as an empty string, but I think it's best to have something explicit like `<remove>`. 

Let me know if anyone prefers an alternative string.

**Comment by volosied** [comment]
My particular scenario involved resources files.  So general removal of a particular would not be possible if it's used in the class files.

**Comment by bjhargrave** [comment]
Closing. A new issue can be opened when this type of feature has a more defined use case.
