### ISSUE TITLE
Maven clean package fails

### ISSUE THREAD

**Issue by plainchanter** [eclipse/transformer#149]
With Maven 3.8.1 on Windows 10, mvn clean package fails with garbage output (JVM ended unexpectedly during test).  

I added the following to the pom.xml:

```
<plugin>
  <groupId>org.apache.maven.plugins</groupId>
  <artifactId>maven-surefire-plugin</artifactId>
  <configuration>
    <testFailureIgnore>true</testFailureIgnore>
  </configuration>
</plugin>
```

and the build of the transformer completed, with the following error:

Failed tests:   testProjectArtifactTransformerPlugin(org.eclipse.transformer.maven.TransformMojoTest): Maven 3.2.4 or better is required

The odd thing is that my Maven is already at that level:

Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)

**Comment by bjhargrave** [comment]
I have no idea what is happening for you. ‘clean package’ works fine for me (macOS) with 3.8.1 and 3.6.3 (the `mvnw` version). Can you run `mvnw clean package`?

**Comment by bjhargrave** [comment]
In looking at the CI build and the build in my (macOS) system, I can see that _NO_ tests are being run for the maven project. So there is something wrong in the configuration of the build which needs to be addressed.

```
[INFO] --- maven-surefire-plugin:2.22.2:test (default-test) @ org.eclipse.transformer.maven ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] 
```
