### ISSUE TITLE
Allow different version updates for different manifest attributes

### ISSUE THREAD

**Issue by tbitonti** [eclipse/transformer#174]
Currently, these manifest attributes are updated, and all with the same simple text replacement:
		useNames.add("DynamicImport-Package");
		useNames.add("Export-Package");
		useNames.add("Import-Package");
		useNames.add("Subsystem-Content");
		useNames.add("IBM-API-Package");
		useNames.add("Provide-Capability");
		useNames.add("Require-Capability");
The request is to allow different version values to be used in different attributes.

For example:
Update "Import-Package" to "[10.0,11)" while updating "Export-Package to "10.0".

**Comment by tbitonti** [comment]
See the related issue #175

**Comment by jhanders34** [comment]
This issue is needed for https://github.com/openliberty/open-liberty/issues/11497

**Comment by tbitonti** [comment]
Package version updates within manifest:

Within OSGi metadata expressed as manifest files, attributes may specify package versions.

The transformer updates these attributes:

    "DynamicImport-Package"
    "Export-Package"
    "Import-Package"
    "Subsystem-Content"
    "IBM-API-Package"
    "Provide-Capability"
    "Require-Capability"

Version updates are made using package versions rules data, a java properties file.  The "-tv" (or "--versions") command line option is used to specify the location of the package versions rules data properties file.

When specifying package version rules data, the property key is a post-rename package name, and the property value is one or more replacement package versions.

The replacement package version is processed as a direct string replacement of a package version value which was parsed out of the manifest attribute value.

When specifying a replacement package version, in addition to meanings assigned for java properties files, '=' and ';' are used to specify attribute specific version updates.

When a single, universal, version replacement is to be made, the property syntax is as a simple key-value pair:

newPackageName=newPackageVersion

When attribute specific values are to be provided, the property value provides a universal (default) replacement value and provides attribute specific values:

newPackageName=defaultPackageVersion;Import-Package=specificVersion1;Export-Package=specificVersion2

That is, the ';' is used to delimit version values, and the '=' is used to indicate an attribute specific replacement.

**Comment by tbitonti** [comment]
See the comment, above, on 27-Sep-2021.  This capability has already been added.
