### ISSUE TITLE
Review location of child properties files for text updates

### ISSUE THREAD

**Issue by tbitonti** [eclipse/transformer#177]
When you do a jakarta-file.properties and have a file name pointing to a rules file, it uses the current working directory or something and doesn't look for the file in the same directory as the file.  So if you have myfiles.propreties with a line of myfile.xml=myfile.properties it won't look for the myfile.properties in the same directory that myfiles.properties is in.

(Possibly already fixed, or working as designed.  Opening as a question until verified as not fixed.)

**Comment by bjhargrave** [comment]
I am pretty sure I have already made changes which will fix this concern.
