### ISSUE TITLE
Better documentation for using command line

### ISSUE THREAD

**Issue by sebersole** [eclipse/transformer#179]
Perhaps my Google-fu simply blows, but I have been unable to find decent documentation/examples of running the transformer from the command line.  All doc/examples I have been able to find make the assumption that there is an executable named `JakartaTransformer`.  But they all gloss over where one gets this executable and how to make it executable (I assume the second will be trivial based on the first)

**Comment by sebersole** [comment]
I've actually seen both `Transformer` and `JakartaTransformer` as the command.  But still never any explanation of the set up.

**Comment by reinhapa** [comment]
I got the same problem here, it would be great to have some samples on how to migrate a existing source base using the CLI.  The only hint I saw was in presentation of @Emily-Jiang at the [MicroProfile 4.1, 5.0 and beyond | JakartaOne Livestream 2021 presentation](https://youtu.be/P9ex_2Kk_HI?list=PLutlXcN4EAwCxiFhy8X7vi4gxqVUNbqkI&t=1207)

**Comment by bjhargrave** [comment]
I have done a major refactoring and, in the latest code, the main CLI class for Jakarta transformation is now `org.eclipse.transformer.cli.JakartaTransformerCLI`.

You can run 

```script
mvn exec:java --file=org.eclipse.transformer.cli -Dexec.arguments="--help" 
```

to see the CLI help. More work is needed, but this where things currently stand.

**Comment by Emily-Jiang** [comment]
Thanks @bjhargrave ! It might be a good idea to put the above comment on readme of this repo so that people can find it easily. When you improve it further, you can update the readme as you go along.

**Comment by reinhapa** [comment]
@sebersole does my addition in [usage](https://github.com/eclipse/transformer#usage) help for the command line?

**Comment by jheadley** [comment]
In case it helps anyone else, I was able to finally make progress by using https://github.com/navikt/dev-jakarta-transform to help me get the job done. After cloning that repo, change the transformer's version in that project's pom.xml to "0.5.0", then follow the steps as outlined. Thank you to the navikt team for making that available.

**Comment by bjhargrave** [comment]
I would recommend anyone use the [maven plugin](https://github.com/eclipse/transformer/tree/main/maven-plugins/transformer-maven-plugin) instead of the CLI if they want to integrate transforming into a maven build.
