### ISSUE TITLE
JavaActionImpl does not handle "--direct" replacement

### ISSUE THREAD

**Issue by rsearls** [eclipse/transformer#186]
Merge of issues 20 and 186:

>> 20: Add JSP Transformation step
>> 186: JavaActionImpl does not handle "--direct" replacement

Updates to string transformation cases:

(1) Perform package updates, both (.) and (/) format cases, to Java and Jsp actions.
(2) Perform direct updates, both per class and global, in the Java action.  Map direct per-class updates to the corresponding java names.

Possibly:

(4) Map per-file text java updates to per-class class updates.

**Comment by tbitonti** [comment]
org.eclipse.transformer.action.impl.ClassActionImpl.transformString(String, String, String)
-- line 962

org.eclipse.transformer.action.impl.JavaActionImpl.transform(BufferedReader, BufferedWriter)
-- no call to perform direct string substitution
