### ISSUE TITLE
Command line rules data additions

### ISSUE THREAD

**Issue by bjhargrave** [eclipse/transformer#25]
From @tbitonti 

Open-liberty, when specifying bundle identity updates, would prefer to specify the identity information at the project level and through command line arguments, instead of through a global rules file. For example:

JavaEE-Bundle-Symbolic-Name: ...
JakartaEE-Bundle-Symbolic-Name: ...
JakartaEE-Bundle-Name: ...
JakartaEE-Bundle-Version: ...
JakartaEE-Bundle-Description: ...

These would be read and processed by BND tooling in the open-liberty build and would be provided to the transformer using a new command line option.

Possibly:

--rule-data ruleName ruleDataLine

"ruleDataLine" would add to the data from the rules properties file matching the specified "ruleName".

**Comment by bjhargrave** [comment]
From @tbitonti 

open-liberty issue: OpenLiberty/open-liberty#12445

**Comment by tbitonti** [comment]
Test plan for immediate package renames:

The test plan is to update a manifest using package rename data.

The test includes package rename data and linked package version data.

Four package names are present in the test data:

The first package name and version are updated by property file data.
The second package name and version are updated by property file data, but that is overwritten by immediate data.
The third package name and version are updated by immediate data.
The fourth package name and version are not updated.

The initial and final package values in the manifest are:

```
javax.package0;version="0.0.0"         jakarta.package0;version="0.0.1"
javax.package1;version="1.0.0"         jakarta.package11;version="1.1.1"
javax.package2;version="2.0.0"         jakarta.package22;version="2.1.1"
javax.package3;version="3.0.0"         jakarta.package3;version="3.0.0"
```

Property file ane immediate data:

```
tier0: javax.package0=jakarta.package0
         javax.package1=jakarta.package1

immediate: javax.package1=jakarta.package11
                   javax.package2=jakarta.package22

tier0: jakarta.package0="0.0.1"
         jakarta.package1="1.0.1"

immediate: jakarta.package11="1.1.1"
                   jakarta.package22="2.1.1"
```

Command line options are:

```
	"-tr", DATA_DIR + '/' + "tier0.renames.properties",
	"-tv", DATA_DIR + '/' + "tier0.versions.properties",

         "-ti", "tr", "javax.package1", "jakarta.package11",
         "-ti", "tr", "javax.package2", "jakarta.package22",

         "-ti", "tv", "jakarta.package11", "1.1.1",
         "-ti", "tv", "jakarta.package22", "2.1.1"
```

**Comment by tbitonti** [comment]
One more commit: Refactoring of the new tests to move common methods to TestUtils.
