### ISSUE TITLE
Executable permission lost when transforming

### ISSUE THREAD

**Issue by gsmet** [eclipse/transformer#275]
Hi,

We are using the Eclipse Transformer to transform some portions of Quarkus and it's working remarkably well. Except for one small issue: when we have executable files in the directory, the executable bit is lost when the file is copied to the new target.

So I have to restore the permissions after the transformation. Which I could do if it was a one-off but we are automatically maintaining a Jakarta branch and we need to keep the permissions even for newly added files.

AFAICS, the BND `IO` class just does a standard copy without keeping the attributes but I'm unsure if you want to change it there or adjust in the Eclipse Transformer itself.

Thanks!

**Comment by bjhargrave** [comment]
Are you using a directory transform? Input directory to output directory?

**Comment by gsmet** [comment]
Yes, exactly, I transform a whole directory which might also contain shell scripts (or a `gradlew` wrapper) with `-o myDir myNewDir`.

**Comment by bjhargrave** [comment]
So I wrote a test to confirm if IO.copy (which uses Files.copy) did not copy the exec bit. On my macOS system, the posix permissions where the same on the target file as the input file.

**Comment by gsmet** [comment]
That's not what I observe here. Now I was using an old version (0.2.0) so maybe things have changed since then.

**Comment by gsmet** [comment]
I will try with 0.4.0 and report back.

**Comment by gsmet** [comment]
Indeed, it looks good with 0.4.0. Sorry about the noise.

BTW, it also fixed some issues with some service files not being renamed so thanks for pushing the release!

**Comment by bjhargrave** [comment]
Sure. No problem. More goodness to come in 0.5.0 in the next month.
