### ISSUE TITLE
Transformation doesn't preserve symlinks

### ISSUE THREAD

**Issue by gsmet** [eclipse/transformer#276]
So this time, I found the issue with 0.4.0. I have checked current `main` of `DirectoryActionImpl` and I don't see symlinks being specifically handled so I think this is still an issue.

We have this thing in the Quarkus tree:
```
lrwxrwxrwx. 1 gsmet gsmet 12 Apr 22 13:50 extensions/kubernetes-service-binding/runtime/src/test/resources/k8s/test-k8s/.hidden-symlink-dir -> .hidden-dir/
```

And after transformation, `.hidden-symlink-dir` is made a standard directory with the content of `.hidden-dir/`:
```
deleted:    extensions/kubernetes-service-binding/runtime/src/test/resources/k8s/test-k8s/.hidden-symlink-dir
new file:   extensions/kubernetes-service-binding/runtime/src/test/resources/k8s/test-k8s/.hidden-symlink-dir/provider
new file:   extensions/kubernetes-service-binding/runtime/src/test/resources/k8s/test-k8s/.hidden-symlink-dir/test-secret-key
new file:   extensions/kubernetes-service-binding/runtime/src/test/resources/k8s/test-k8s/.hidden-symlink-dir/type
```

**Comment by bjhargrave** [comment]
I am not sure what you think the correct behavior should be. If you are copying a directory to a new directory, I am not sure it is smart to copy symlinks rather than following the link. That is, using `LinkOption.NOFOLLOW_LINKS` seems like a bad idea since we can end up mutating the symlinked directory content.

**Comment by gsmet** [comment]
The symlink should be kept as is and not made a directory. I don't want the transformer to alter the content of the directory (which it is doing right now).

**Comment by bjhargrave** [comment]
So if DirectoryActionImpl should detect that a directory is a symlink, it should only copy the symlink to the output folder but otherwise do not process the symlink directory contents? 

What if the file is a symlink? For consistency, we would want do the same. That is, only copy the symlink by not transform the file.

I don't think the above is the correct behavior for transformer.

**Comment by gsmet** [comment]
Well my opinion is that it's exactly the behavior you want.
Your symlink might point to a file or a directory but there's no reasons to transform it: symlinks are there for a reason, they shouldn't be resolved. You shouldn't change the repository content.

Just take our repository for example: we specifically have a symlink to test something and transforming the source code just makes the test pointless as the symlink is now a directory.
The transformer shouldn't change the structure of the directory, only the content of the files.

**Comment by bjhargrave** [comment]
The transformer DirectoryActionImpl is copying and transforming a directory and its contents. You want symlinks to be ignored except for copying the symlink to the appropriate target directory. Transformer can also change the directories such as when a package is renamed, so the output directory names can change. So if package `a.b.c` is renamed to package `d.e.f` and `b` is a symlink, what should the output directories look like? `d/b/c` (copy the symlink with the original name)? Or `d/e/c` (copy the symlink but rename it)?

There seem to be many cases where unexpected things will happen when symlinks are just copied and not followed. Normal course of operations is to follow symlinks. Not following symlinks requires specifying some option and is not the normal case.

**Comment by gsmet** [comment]
I don't mind following symlinks. What is a problem is transforming symlinks to something else. It completely changes the semantic of the original content.

In my case, it breaks a test as it makes it completely irrelevant. I really don't think the transformer should do that and alter the semantic of the transformed content.

Now if my only option is to restore the symlink after the transformation, I will do it but IMHO this is very problematic, especially since I was lucky enough to notice it and I'm pretty sure a lot of people will miss this behavior.

The transformer shouldn't alter the semantic of the original content.

**Comment by bjhargrave** [comment]
I just don't see how transformer can copy a directory and transform it contents if just the symlink is copied.

I think you simply have a special case which you will need to handle outside of the transformer.

**Comment by gsmet** [comment]
Maybe I wasn't clear but the symlink is deep inside a directory. I don't want the transformer to transform things in it, nor am I asking the transformer to do anything about it.
I'm transforming a project and in this project, it happens that deep inside there is a symlink used to test that something is working with a symlink.

**Comment by gsmet** [comment]
> I think that a better solution is for the test case to create the symlink before running the test instead of relying upon the symlink existing in the git repo/transformed tree.

Well maybe but that's how it is. And I still think the transformer shouldn't alter the structure of the original content.

Having a symlink in the original directory and ending with a copy of the symlinked content in the target directory doesn't seem like what I would expect from the transformer.

Now if you don't want to change this behavior, I suppose I will have to delete the content and recreate the symlink in a shell script but it's certainly not ideal.

**Comment by bjhargrave** [comment]
Closing.
