### ISSUE TITLE
[Question] Namespace renaming on Annotations

### ISSUE THREAD

**Issue by c-koell** [eclipse/transformer#277]
We have a Class that looks like
```
@FacesRenderer(componentFamily = "javax.faces.Output", rendererType = "my.custom.ContentAreaRenderer")
public class ContentAreaRenderer extends Renderer {
..
}
```
We are using the maven plugin to generate jakarta artifacts. I have found that the value of the componentFamily will not be changed automatically.

Do i have to define a custom rule for that ?

Thanks for any help !

**Comment by bjhargrave** [comment]
What version of transformer are you using? I would think the transformation of the String constant "javax.faces.Output" would be handled by the `javax.faces`->`jakarta.faces` package rename rule.

**Comment by c-koell** [comment]
We are using 0.2.0. I will update to 0.4.0 and try it again ...

**Comment by c-koell** [comment]
Thank you for your quick response ! With 0.4.0 the value will be changed to "jakarta.faces.Output"
