### ISSUE TITLE
Package names in Deployment Descriptor and JSP/JSF files may not be transformed

### ISSUE THREAD

**Issue by 11rx4f** [eclipse/transformer#291]
## Problem Description
Package names in Deployment Descriptor and JSP/JSF files may not be transformed.

## Steps to reproduce
The problem occurs when a Jakarta EE related file such as following examples are given as the input of Transfomer.

* Example 1: web.xml
```
    <error-page>
      <exception-type>javax.servlet.ServletException</exception-type>
      <location>/error.html</location>
    </error-page>
```

* Example 2: glassfish-resources.xml
```
<resources>
  <connector-connection-pool max-pool-size="250" steady-pool-size="1" name="jms/HelloQCF" resource-adapter-name="jmsra" connection-definition-name="javax.jms.QueueConnectionFactory"></connector-connection-pool>
  <connector-resource pool-name="jms/HelloQCF" jndi-name="jms/HelloQCF"></connector-resource>
  <admin-object-resource res-adapter="jmsra" res-type="javax.jms.Queue" jndi-name="jms/InQueue">
    <property name="Name" value="InQueue"></property>
  </admin-object-resource>
  <admin-object-resource res-adapter="jmsra" res-type="javax.jms.Queue" jndi-name="jms/OutQueue">
    <property name="Name" value="OutQueue"></property>
  </admin-object-resource>
</resources>
```

* Example 3: JSP related files (.jspf,.jspx,tagf,.tagx)
```
<jsp:directive.page import="javax.servlet.http.Cookie, javax.net.ssl.HttpsURLConnection, java.net.URL"/>

<%
javax.servlet.jsp.JspWriter stream = out;
%>
```

* Example 5: JSF(Facelets) files (.xhtml)
```
<f:validateBean validationGroups="javax.validation.groups.Default"/>
<h:outputScript name="hello.js" library="javax.faces" target="head"/>
```

## Cause
Problems with the GlassFish Deployment Descriptor, JSP, and JSF are caused by missing descriptions in the following files.

https://github.com/eclipse/transformer/blob/main/org.eclipse.transformer.jakarta/src/main/resources/org/eclipse/transformer/jakarta/jakarta-text-master.properties

The problem with some packages not converted in web.xml is due to missing descriptions in the following files.   

https://github.com/eclipse/transformer/blob/main/org.eclipse.transformer.jakarta/src/main/resources/org/eclipse/transformer/jakarta/jakarta-xml-dd.properties

## Impact of Issue
Since they are commonly used by Jakarta EE, it would be very inconvenient if they are not converted by default.

**Comment by bjhargrave** [comment]
> * web.xml

Agree. `web.xml` is already included for transformation. We just need to add more details. I made PR #310.



> * glassfish-resources.xml

It seems like there are a number of glassfish-*.xml files. I don't know much about them all and how they compare to specified Jakarta EE files.



> * JSF(Facelets) files (.xhtml)

`*.xhtml` seems a too broad glob to use for default transformations.

**Comment by bjhargrave** [comment]
I think this can be closed since the rules have been improved.
