### ISSUE TITLE
TransformerCLI logging cleanup

### ISSUE THREAD

**Issue by tbitonti** [eclipse/transformer#297]
Ref:

/org.eclipse.transformer.cli/src/main/java/org/eclipse/transformer/cli/TransformerCLI.java

	// TODO: Usual command line usage puts SysOut and SysErr together, which
	// results in the properties writing out twice.

	private void preInitDisplay(String message) {
		PrintStream useSysOut = getSystemOut();
		// PrintStream useSysErr = getSystemErr();

		useSysOut.println(message);
		// if ( useSysErr != useSysOut ) {
		// useSysErr.println(message);
		// }
	}

**Comment by tmrpavan** [comment]
I would like to work on this issue. Can you assign this to me.
