### ISSUE TITLE
Are USAGE and HELP command line return codes correct?

### ISSUE THREAD

**Issue by tbitonti** [eclipse/transformer#298]
Ref:

/org.eclipse.transformer.cli/src/main/java/org/eclipse/transformer/cli/TransformerCLI.java

		// TODO: Are the USAGE and HELP return codes correct?

		if ((getArgs().length == 0) || hasOption(AppOption.USAGE)) {
			usage(getSystemOut());
			return logResult(ResultCode.SUCCESS_RC);
		} else if (hasOption(AppOption.HELP)) {
			help(getSystemOut());
			return logResult(ResultCode.SUCCESS_RC);
		}

**Comment by bjhargrave** [comment]
This seems related to #295.
