### ISSUE TITLE
Properties transformation behavior needs further explanation

### ISSUE THREAD

**Issue by tbitonti** [eclipse/transformer#300]
Ref:

/org.eclipse.transformer/src/main/java/org/eclipse/transformer/TransformProperties.java

					// TODO: We might want to skip an update in a specific
					//       case.  A blank/empty update might be used to
					//       encode this.
					if ( nameBuilder.length() != 0 ) {
						throw new IllegalArgumentException("Package version syntax error: Version missing for package [ " + newPackageName + " ] and attribute [ " + nameBuilder.toString() + " ]");

**Comment by bjhargrave** [comment]
This is related to #290.
