### ISSUE TITLE
Unify 'replacePackage' and 'replacePackages in the signature rule implementation

### ISSUE THREAD

**Issue by tbitonti** [eclipse/transformer#307]
Ref:

/org.eclipse.transformer/src/main/java/org/eclipse/transformer/action/impl/SelectionRuleImpl.java

	// TODO: Unify the implementations of 'replacePackages'
	// and 'replacePackage'.

	private String replacePackages(String text, Map<String, String> renames) {

**Comment by nitin1chandani** [comment]
can you assign me

**Comment by 11rx4f** [comment]
As Eclipse Transformer is a community project we'd welcome a PR to fix the issue.
