### ISSUE TITLE
output directory is not correct when separater are added at the end of inputfile path

### ISSUE THREAD

**Issue by 11rx4f** [eclipse/transformer#317]
##  Environment Details
* Transformer Version: 0.5.0
* JDK version: 11
* OS: Windows Server 2019, Red Hat Enterprise Linux 7.9

## Problem Description
If "/" or "\\" are added at the end of inputfile path, and outputfile path isn't specified, files are created under the output_ directory.

## Steps to reproduce
```
>java -jar org.eclipse.transformer.cli/target/org.eclipse.transformer.cli-0.5.0-SNAPSHOT.jar /work/test/directory1/
```

Originally, "output_directory1" directory should be created under "/work/test"
However, converted files are output under "/work/test/directory1/output_" directory.  

```
[main] INFO Transformer - Input [ /work/test/directory1 ]
[main] INFO Transformer - Output [ /work/test/directory1/output_ ]
```

## Cause

https://github.com/eclipse/transformer/blob/a4002900aed92a4ec931cec37c778ec98dd816a4/org.eclipse.transformer/src/main/java/org/eclipse/transformer/Transformer.java#L1012-L1019

useOutputName has the wrong value because setOutput() checks the position of the last slash in inputName.   

### Example
* inputName:     "/work/test/directory1"
* inputPrefix:   "/work/test/directory1"
* inputSuffix:   ""
* useOutputName: "/work/test/output_"

Also,
https://github.com/eclipse/transformer/blob/a4002900aed92a4ec931cec37c778ec98dd816a4/org.eclipse.transformer/src/main/java/org/eclipse/transformer/Transformer.java#L1073-L1075
does not check whether the output directory is under the input directory. So the output directory is created in the input directory.

**Comment by bjhargrave** [comment]
Can you make a PR with a proposed fix?
