### ISSUE TITLE
TransformerCLI does not update any source code

### ISSUE THREAD

**Issue by reinhapa** [eclipse/transformer#364]
I try to transform the source of an existing [Sandbox](https://github.com/reinhapa/Sandbox/) project using the current main branch and  no update was made even though there are old JavaEE imports in this project.

The output of the Transformer tool using the options `TransformerCLI Sandbox -d -td` are as follows:

```
Copyright (c) Contributors to the Eclipse Foundation
org.eclipse.transformer.cli.TransformerCLI Version [ 0.6.0-SNAPSHOT ]

[main] INFO Transformer - Input [ /home/pr/git/reinhapa/Sandbox ]
[main] INFO Transformer - Output [ /home/pr/git/reinhapa/output_Sandbox ]
[main] INFO Transformer - All resources will be selected
[main] INFO Transformer - Action selected for input [ Sandbox ]: Directory Action
[main] INFO Transformer - Input  [ Sandbox ] as [ /home/pr/git/reinhapa/Sandbox ]
[main] INFO Transformer - Output [ /home/pr/git/reinhapa/output_Sandbox ]
[main] INFO Transformer - [  All Resources ] [  52508 ] Unaccepted [      0 ]   Accepted [  52508 ]
[main] INFO Transformer - [  All Unchanged ] [  52508 ]     Failed [      0 ] Duplicated [      0 ]
[main] INFO Transformer - [    All Changed ] [      0 ]    Renamed [      0 ]    Content [      0 ]
[main] INFO Transformer - Transformer Return Code [ 0 ] [ Success ]
```

Do I miss some additional options to be specified or did I made some other mistake?

**Comment by bjhargrave** [comment]
`org.eclipse.transformer.cli.TransformerCLI` does not have any predefined transformation rules so you must configure any transformation rules on the command line.

If you want to use the predefined Jakarta EE transformation rules, you would want to use `org.eclipse.transformer.cli.JakartaTransformerCLI`.

https://github.com/eclipse/transformer/blob/cfea3e64a59119de77bd9ce60d54fb82f17292fa/org.eclipse.transformer.cli/src/main/java/org/eclipse/transformer/cli/JakartaTransformerCLI.java#L33-L36

**Comment by reinhapa** [comment]
@bjhargrave Thanks for the solution for me. Seems I totally overlooked this.
