### ISSUE TITLE
Reconsider using `java.nio.ByteBuffer` instead of `byte[]` or `InputBuffer` 

### ISSUE THREAD

**Issue by bjhargrave** [eclipse/transformer#4]
ByteBuffer is a well known type providing a view over a byte array.

**Comment by bjhargrave** [comment]
From @ropalka

Such transformer API should support at minimum both ByteBuffer and byte[] types.

**Comment by ropalka** [comment]
@bjhargrave After some iterations our Transformer API [1] is using Resource abstraction which is using byte[] param to represent resource content. Resource can be any archive entry like class file, xml file, properties file, etc. ( CC @scottmarlow )

[1] https://github.com/wildfly-extras/batavia/blob/master/api/src/main/java/org/wildfly/transformer/Transformer.java

**Comment by bjhargrave** [comment]
54c8f1192c01f1d21945b9de34da94bf0acf4e15 updates the code to have a ByteData type which encapsulates a name and a ByteBuffer.
