### ISSUE TITLE
Transformer RC, Alpha, or Beta ready for Jakarta EE 9 Milestone in June?

### ISSUE THREAD

**Issue by kwsutter** [eclipse/transformer#40]
The Jakarta EE 9 Milestone "release" is planned for June 2020:
- June 12, Development Complete
- June 19, Testing Complete
- June 23, "announcement"

It would be great if we could include a Transformer deliverable in our blogs, presentations, and "announcement" literature.  Some type of pre-built download (milestone, RC, Alpha, whatever) available via Maven would be excellent.  Also, having some type of simple instructions or README to explain how to use the Transformer with applications that might want to try out the Jakarta EE 9 Milestone deliverable would be helpful.

Thanks!

**Comment by bjhargrave** [comment]
I just merged the new maven build, so snapshot artifact are now available from https://oss.sonatype.org/content/repositories/snapshots/org/eclipse/transformer/

For use by others, probably the main thing we need to focus on in this project is documentation on how to use what we now have.

**Comment by bjhargrave** [comment]
We have a new maven build but are struggling to get the Eclipse provisioned gpg key to work for signing the artifacts which would be needed to publish a non-snapshot release. 

This is being worked in https://bugs.eclipse.org/bugs/show_bug.cgi?id=563870.

**Comment by bjhargrave** [comment]
I think we can close this as the time has long since passed.
