### ISSUE TITLE
SwitchMap and SWITCH_TABLE references should be updated

### ISSUE THREAD

**Issue by dblevins** [eclipse/transformer#46]
This is an optional enhancement that doesn't materially affect runtime execution, but still could be nice.

When you refer to an enum in a switch/case the JVM actually compiles that into a int-based switch/case indirectly using the ordinals of the enum values as the ints.  The ordinal references are not hardcoded into the compiled class so that if the enum was changed in the future old switch cases referring to still-valid enum names would still work.

To achieve this the VM generates an inner-class for you and in that inner-class is a field that holds a int-to-int mapping which is populated at runtime (effectively, old ordinals to new ordinals).  The name of this field will look like this:

 - `$SwitchMap$javax$faces$component$visit$VisitResult`

In this case, the enum being referenced is `javax.faces.component.visit.VisitResult`.  Here's an example of how this looks via the ASMifier:

 - https://github.com/dblevins/tomee-analysis/blob/ff44d86b2670b4355d51e2ff85735da7273328ca/apache-tomee-microprofile-8.0.3-SNAPSHOT.zip/apache-tomee-microprofile-8.0.3-SNAPSHOT/lib/myfaces-api-2.3.6.jar/jakarta/faces/component/UIData$2-asmified.java#L32

Though this field has what appears to be a reference to a renamed class the code will still run fine as in truth the generated field name could be anything.

That said, any introspection tools, including decompilers may break.  These tools are aware of the naming format and use it to imply the source code.

It's not critical, but we should eventually fix this as time permits.

**Comment by bjhargrave** [comment]
>     * $SwitchMap$javax$faces$component$visit$VisitResult

This seems like a compiler implementation detail and not part of JLS or JVMS. We would need this to be part of a specification so that it could be reliably fixed to all. For example, does ECJ using the same naming convention as javac? Where is this naming convention documented?

[JLS 8](https://docs.oracle.com/javase/specs/jls/se8/html/jls-14.html#jls-14.11) does not mention it.

**Comment by dblevins** [comment]
I'm not entirely sure, but I'll ask around and see if I can dig up some answers.

**Comment by bjhargrave** [comment]
It is possible this field name could be transformed with a direct string rule applied to the utf8 constant holding the field name. And regex direct string rule support would be handy here!

**Comment by dblevins** [comment]
That sounds workable.  The limiting factor being as a user I'd definitely not want to be writing those regexes.  But potentially if we split this into two different bits of functionality, it could potentially be palatable.

Seems like one aspect the basic ability to do a regex replacement and perhaps to scope it; maybe by default it hits what the user sees as strings, but with the right setting could also target field names and references to those names.

Then there could potentially be some various kinds of logic to seed those regexs for users that the user could turn on/off at will.  This one would be harder, but could potentially save on a lot of user errors.
