### ISSUE TITLE
Multithreaded approach

### ISSUE THREAD

**Issue by jeanouii** [eclipse/transformer#460]
On relatively small archives, the Eclipse Transformer by default takes forever to do its job. 

The was is around 50MB, and it takes more than an hour on my MacBook Pro 2022 (Apple Silicon).
I was wondering if for a given JAR action we could not at least run all Class action in parallel (fork-join?).

What do you think?

**Comment by bjhargrave** [comment]
This does not sound correct. It is not that slow on my M1 mac. I processed a 70MB jar in under a minute. Are you using a Java VM for Apple Silicon? Or running a Java VM for Intel under Rosetta?

**Comment by jeanouii** [comment]
My current WAR is 51MB and takes 700s with the Eclipse Transformer and 21s with Apache Tomcat Migration tool.
Of course it's not an apple to apple comparison because the Eclipse Transformer does a bit more. But the gap is also huge. So I'm trying to figure out what I can do to improve the situation.

One thing I see taking a lot of time is the direct replacement. Tomcat has a big compiled regexp and then just calls replace with it. 

The Eclipse Transformer iterates over around 600 entries in a Map of strings and does a contains+replace.
Let's say a Pattern replace takes the same time as contains+replace --> the transformer does 600 times the same operation for all entries in the class.

Wondering what is the reason if any for this choice.
Noticed the comment 

> 		// Perform all possible substitutions, in order.
>		//
>		// Match using a simple 'contains' test. Later,
>		// a regular expression might be used.
