### ISSUE TITLE
Wrong transformation of JSR 305 annotations

### ISSUE THREAD

**Issue by jeanouii** [eclipse/transformer#468]
Hi,

I found a case where some JSR 305 annotations get converted over to jakarta namespace. As far as I am aware of, they aren't part of the new jakarta namespace, so should not be converted by default.

Here is an example
https://github.com/google/guava/blob/master/guava/src/com/google/common/io/package-info.java

**Comment by bjhargrave** [comment]
Transformer operates on a package basis with respect to changing package names. The `javax.annotation` package name is part of the Jakarta Annotations spec: https://jakarta.ee/specifications/annotations/1.3/apidocs/javax/annotation/package-summary.html. 

It is unfortunate that `javax.annotation` package is not "sealed". But for the default Jakarta transformation rules, the Jakarta Annotation specification indicated that the  `javax.annotation` package should be renamed to `jakarta.annotation`.

**Comment by jeanouii** [comment]
`jakarta.annotation.Nullable` and `jakarta.annotation.Notnull` were in the JSR 305 and got converted so they have their equivalent. But, how can I solve the other ones being wrongly converted?

I looked at the code, but `private ClassTypeSignature transform(ClassTypeSignature inputType) {}` does only provide the package so I can't even tweak the renames.properties with something custom for my case.

**Comment by jeanouii** [comment]
Is there a way we could move them back to javax?
The replacePackage seems to only use the package to do the substitution. If we would get the entire FQCN that'd be possible, I don't think this is currently possible.

**Comment by jeanouii** [comment]
Closing also this one
