### ISSUE TITLE
Java 21-ea issue

### ISSUE THREAD

**Issue by beikov** [eclipse/transformer#475]
I just created https://github.com/bndtools/bnd/issues/5689 because that is the actual root cause for the issue, but I guess the Eclipse Transformer should update the dependency once the issue is fixed.

**Comment by beikov** [comment]
It seems the bnd version 6.3.1 which the transformer 0.5.0 build upon does not have this issue anymore. Sorry for the noise

**Comment by beikov** [comment]
Unfortunately, I spoke too fast. Had an older JDK 21 locally which lacked a fix. Re-opening this issue for updating to the bndtools version produced after fixing https://github.com/bndtools/bnd/issues/5689

**Comment by OndroMih** [comment]
Hi @beikov , is this fixed in bnd 7.0.0? Did you try to use Eclipse Transformer with bnd 7.0.0?

**Comment by bjhargrave** [comment]
The issue is fixed on Bnd 7.0 but Transformer cannot update to 7.0 without also removing support for running on Java 8 which is still a requirement by some users. Bnd 7.0 requires Java 17. However, you should be able to use Transformer with Bnd 7.0 yourself but substituting in the Bnd 7.0 jars instead of the 6.3.1 jars (and using Java 17.)

**Comment by bjhargrave** [comment]
> So this issue probably happens only in some cases, not in general.

Yes. It depends if the compiler emits an attribute in the format which Bnd incorrectly handled.

**Comment by beikov** [comment]
>Hi @beikov , is this fixed in bnd 7.0.0? Did you try to use Eclipse Transformer with bnd 7.0.0?

Yes, 7.0.0 fixes the problem, as did 7.0.0-SNAPSHOT.

>I tried Eclipse transformer 0.5.0 on my sample projects with Java 21 and all builds pass: https://github.com/OmniFish-EE/upgrading-jakarta-ee-applications. So this issue probably happens only in some cases, not in general.

>I agree that a good solution is to use the current Transformer and only substitute Bnd jars I was only curious if it helps @beikov because I can't reproduce his issue on my sample projects.

I updated bnd in the plugin dependencies conditionally i.e. only when I compile with Java 21+ I will set the update the bnd version to 7.0.0. It's not ideal, but I understand that some projects want to move on and update their minimum Java dependency.
