### ISSUE TITLE
Transformer Maven Plugin

### ISSUE THREAD

**Issue by dblevins** [eclipse/transformer#48]
@jgallimore has written a Maven Plugin that allows you to transform the artifacts produced and re-attach them to the Maven module with a new classifier of your choosing.

Here's what the plugin configuration looks like:

```
      <plugin>
        <groupId>org.tomitribe.transformer</groupId>
        <artifactId>transformer-maven-plugin</artifactId>
        <version>0.0.8</version>
        <configuration>
          <classifier>jakartaee9</classifier>
        </configuration>
        <executions>
          <execution>
            <goals>
              <goal>run</goal>
            </goals>
            <phase>package</phase>
          </execution>
        </executions>
      </plugin>

```

This is currently living in a fork that needs to be rebased to the new repo location so we can submit a PR.  The groupId `org.tomitribe.transformer` is temporary just so we can ensure we'll be able to have a release of it far before the TomEE release before the Jakarta EE 9 milestone release.

If others really want this badly now "asap" we can try to prioritize a PR for it.  We're currently heads down.

**Comment by dblevins** [comment]
Here's the fork that plugin is currently living in:

 - https://github.com/tomitribe/transformer

**Comment by OrangeDog** [comment]
Does @jgallimore have any documentation for the plugin? Ideally in standard maven plugin documentation format, but just some examples would be better than nothing.
