### ISSUE TITLE
Unable to run Eclipse Transformer on Java 21 using the Maven plugin

### ISSUE THREAD

**Issue by mnriem** [eclipse/transformer#519]
To make it work I had to add the following dependency to the 0.5.0 version of the Maven plugin:

```
<dependency>
  <groupId>biz.aQute.bnd</groupId>
  <artifactId>biz.aQute.bnd</artifactId>
  <version>7.0.0</version>
</dependency>
```

**Comment by bjhargrave** [comment]
Yes, this is a known issue. See #475.

The work around is to configure the plugin to use the 7.0.0 versions of the bnd dependencies.

See https://github.com/eclipse/transformer/issues/475#issuecomment-1804494175 for why we cannot update this build to use bnd 7.0.0.

**Comment by mnriem** [comment]
@bjhargrave Can we get this documented somewhere prominent? This took way to much time to find out and as Java 21 is going to be more common as it has been out now for a while ....

**Comment by bjhargrave** [comment]
Perhaps you can make a PR for the project readme?

**Comment by mnriem** [comment]
@bjhargrave  See https://github.com/eclipse/transformer/pull/529 for the PR
