### ISSUE TITLE
Parameter 'extensions' is unknown for plugin 'transformer-maven-plugin:0.5.0:jar

### ISSUE THREAD

**Issue by OrangeDog** [eclipse/transformer#536]
The documentation for the Maven plugin says:

> When using this goal without specifying a classifier, the plugin must be configured with `<extensions>true</extensions>` in order to coordinate with the `maven-jar-plugin`.

However, there is no such property documented, and indeed it does not work:

> [WARNING] Parameter 'extensions' is unknown for plugin 'transformer-maven-plugin:0.5.0:jar (default)'
> [ERROR] Failed to execute goal org.eclipse.transformer:transformer-maven-plugin:0.5.0:jar (default) on project test: In order to use the transformer-maven-plugin packaging goal jar without a classifier, \<extensions>true\</extensions> must be set on the plugin configuration

**Comment by bjhargrave** [comment]
It is not part of the plugin's configuration but it is part of the pom to add the plugin as a build extension. See https://maven.apache.org/guides/mini/guide-using-extensions.html#build-extension.

For example, see:

https://github.com/eclipse/transformer/blob/49a789262634e84e7d9e40d1e571f0a9a62e8ecf/maven-plugins/transformer-maven-plugin/src/it/simple-jar/pom.xml#L55-L64
