### ISSUE TITLE
maven-jar-plugin does not run when transformer-maven-plugin is in pom.xml

### ISSUE THREAD

**Issue by zombi170** [eclipse/transformer#675]
We have a bigger project A and one of the module in this project is used by an other project B. Project A still uses JavaEE, however project B just changed to Jakarta. So what I would like to implement is to transform only this module to a separate module-JAKARTA.jar file while in the meantime keeping the original module.jar as well during maven package. What the issue is that maven-jar-plugin, which would create the original .jar file does not run for some reason when I implement the transformer-maven-plugin inside the pom, even when I set the skip argument to true inside the transformer plugin. I am not sure if this is intended or a bug, but if it is intended is there a way to implement my use-case as I described above?

How I am trying to use the transformer-maven-plugin:
```xml
<plugin>
    <groupId>org.eclipse.transformer</groupId>
    <artifactId>transformer-maven-plugin</artifactId>
    <version>0.5.0</version>
    <extensions>true</extensions>
    <configuration>
        <rules>
            <jakartaDefaults>true</jakartaDefaults>
        </rules>
    </configuration>
    <executions>
        <execution>
            <id>transform-to-jakarta</id>
            <goals>
                <goal>jar</goal>
            </goals>
            <configuration>
                <artifact>
                    <groupId>${project.groupId}</groupId>
                    <artifactId>${project.artifactId}</artifactId>
                </artifact>
                <buildDirectory>${project.build.directory}/jakarta</buildDirectory>
                <baseName>${project.build.finalName}-JAKARTA</baseName>
                <attach>false</attach>
            </configuration>
        </execution>
    </executions>
</plugin>
```

**Comment by bjhargrave** [comment]
This is as designed. When you use the `jar` goal of `transformer-maven-plugin` plugin, it takes over the jar operation. 

https://github.com/eclipse/transformer/blob/0d94c306c8c2a9ba8864327d3f14cdc1c62deffa/maven-plugins/transformer-maven-plugin/src/main/java/org/eclipse/transformer/maven/TransformerMavenLifecycleParticipant.java#L34-L47

If you want to use the `maven-jar-plugin` to perform the `jar` goal, then you probably want to use the [`transform` goal](https://github.com/eclipse/transformer/tree/main/maven-plugins/transformer-maven-plugin#transform-goal) of the `transformer-maven-plugin` plugin.

**Comment by zombi170** [comment]
Thanks for the tip, now it seems to be working if I create a copy of the .jar file with maven-assembly-plugin and I transform the copy with the transformer.
