### ISSUE TITLE
ConverterId in JSF files not transformed 

### ISSUE THREAD

**Issue by udengaardandersent-ELS** [eclipse/transformer#695]
## Problem Description
Package names in JSP/JSF files may not be transformed.

### Example 1: sample.xhtml
Have text fields hooked together with converter strategy
```
<p:field label="between"
	layout="inline" labelPosition="between year">
	<p:textfield value="#{cc.attrs.filter.fromYear}">
	<f:converter converterId="javax.faces.Integer"/>
	</p:textfield>
</p:field>
<p:field label="and" layout="inline" labelPosition="and">
	<p:textfield value="#{cc.attrs.filter.toYear}">
	<f:converter converterId="javax.faces.Integer"/>
	</p:textfield>
</p:field>
```

I tested converting a large javaEE webapp and discovered some errors on specific pages, and tracked the error related to not locating "javax.faces.Integer".

I did manually adjust this specific page with new identifier "jakarta.faces.Integer". 
Next recompiling war to javaEE8, then transform to EE10 and running it on tomcat10+ and the pages work as expected.

Is this outside the scope of the transformer, does it only apply for java classes?

**Comment by bjhargrave** [comment]
The transformer can also transform text in non-java files. You may need to specify the necessary configuration to get your use case addressed.
