### ISSUE TITLE
More cleanly define core java API; refactor core command line API and core java API into distinct components

### ISSUE THREAD

**Issue by tbitonti** [eclipse/transformer#74]
This issue is to create a more well defined core java API and to cleanly separate the core command line API from the core java API.

Current project structure has a tightly coupled and thick core command line interface which provides a front-end to the (theoretical) core java API.  While the java API can be invoked as a public API, the API is too heavy to be a proper API.

Having a more well defined core java API, the core command line API should be placed in a separate component.  However, common utilities, for example, for reading rules data from properties files, should be retained as a part of the core java API for use by the command line and other APIs, for example, for use by maven or gradle plugins.

**Comment by bjhargrave** [comment]
This was done in https://github.com/eclipse/transformer/pull/202. There is now a org.eclipse.transformer artifact holding the core API and a org.eclipse.transformer.cli artifact holding the CLI implementation.
