### ISSUE TITLE
String Transformation Fails in Certain Scenarios

### ISSUE THREAD

**Issue by volosied** [eclipse/transformer#79]
The following code snippet is not changed.
Line 350: `          this.writer.print("(javax.servlet.jsp.tagext.JspFragment ");` 
[GenerateTagFileVisitor.class.zip](https://github.com/eclipse/transformer/files/4827747/GenerateTagFileVisitor.class.zip)

I've tried the following transformation rules 

Renames:
javax.servlet.jsp.tagext=jakarta.servlet.jsp.tagext

Direct
javax.servlet.jsp.tagext=jakarta.servlet.jsp.tagext

In neither case, does not transform that particular line.  But the rule is correct because I get a transformation in other parts of the code: 
Line 216:     
`this.writer.print("public class " + this.tagFileFiles.getClassName() + " extends jakarta.servlet.jsp.tagext.SimpleTagSupport");`
 Line 329:  
`this.writer.print("jakarta.servlet.jsp.tagext.JspFragment ");`

A similar situation occurs with this line too:

` writer.print("(javax.servlet.jsp.tagext.SimpleTag) this ));");`

[BaseTagGenerator.class.zip](https://github.com/eclipse/transformer/files/4827788/BaseTagGenerator.class.zip)

**Comment by bjhargrave** [comment]
I think you need a exact string match. `"(javax.servlet.jsp.tagext.JspFragment "` is a string with a leading `(` and a trailing ` `. So it will not match `javax.servlet.jsp.tagext`. 

String replace is hard and it is not necessarily safe to go looking into string contents and replacing subsequences.

We are discussing adding more expressive regex/replacement support for string constant transformation. See #77, #46, #44, and #43 for other string replacement discussion.

To make progress with your use case, I would suggest making sure any class names are simple sting constants with no leading or trailing characters. For example:

```java
this.writer.print("(");
this.writer.print("javax.servlet.jsp.tagext.JspFragment");
this.writer.print(" ");

this.writer.print("public class ");
this.writer.print(this.tagFileFiles.getClassName());
this.writer.print(" extends ");
this.writer.print("javax.servlet.jsp.tagext.SimpleTagSupport");
```

**Comment by volosied** [comment]
Thank you for the feedback, @bjhargrave. I've split up the lines, and the transformation was successful.

**Comment by scottmarlow** [comment]
Hi apologies if this is unrelated but I found this issue when trying to understand a JSP ```javax.servlet.jsp.tagext.Tag cannot be resolved to a type``` failure.

For transforming applications EE8 => EE 9 that have JSP, should the org.eclipse.transformer.cli/src/main/resources/org/eclipse/transformer/jakarta/jakarta-direct.properties handle javax.servlet.jsp.tagext.Tag?  

Or should ./org.eclipse.transformer.cli/src/main/resources/org/eclipse/transformer/jakarta/jakarta-renames.properties handle javax.servlet.jsp.tagext.Tag => jakarta.servlet.jsp.tagext.Tag?

**Comment by scottmarlow** [comment]
I see that the jakarta-direct.properties can let us specify Java constant values to replace that are specific to a JSP handling class like org.apache.jasper.compiler or others that could be used, so now understand that there isn't as much to share unless it is specific to certain JSP handlers/compilers (so we could share definitions for common JSP handlers).

**Comment by volosied** [comment]
Hi @scottmarlow,

You are correct. The [_jakarta-direct.properties_](https://github.com/eclipse/transformer/blob/2cda495d71c54a529f89483fc7224013f9ce0376/org.eclipse.transformer.cli/src/main/resources/org/eclipse/transformer/jakarta/jakarta-direct.properties#L8) file is used for string constants, while [_jakarta-renames.properties_](https://github.com/eclipse/transformer/blob/2cda495d71c54a529f89483fc7224013f9ce0376/org.eclipse.transformer.cli/src/main/resources/org/eclipse/transformer/jakarta/jakarta-renames.properties#L18-L22) can be used for class references and string constants. The rule placement depends on your needs. 

I use a decompiler, such as JD-GUI,  to verify what was transformed. If `javax.servlet.jsp.tagext.Tag `is part of a string, you may have encountered a similar issue as I had where it didn't transform until the string was broken up in the java file?

**Comment by bstansberry** [comment]
@volosied That's exactly what @scottmarlow and I were seeing with WildFly's use of undertow/jastow. Breaking up the strings solves the problem.  Thank you for these issues; they definitely helped us understand how this works.

**Comment by tbitonti** [comment]
Hi.  Per @bjhargrave on 24-Jun-2021, this is working as designed.  String replacement requires exact matches so to avoid accidental replacements.
