### ISSUE TITLE
Support for pluggability of various class file transformers

### ISSUE THREAD

**Issue by bjhargrave** [eclipse/transformer#8]
From @scottmarlow

Add ability to plug different transformer implementations in, such that a no dependency transformer can be used, as well as an ASM based transformer, and potentially others. These transformers will be based on github.com/wildfly-extras/batavia which are working prototypes. The goal being that the BND transformer can be enabled, as well as the other third-party transformers.

**Comment by bjhargrave** [comment]
From @ropalka

Ideally introducing an integration API or SPI.

**Comment by bjhargrave** [comment]
The project is now using a much slimmed down dependency from Bnd. So the concern about size is addressed.

I don't think it is wise or useful to invest in an SPI for substituting class file transforming engines. If one wants to do that, different class file rules can be authored. So I think we should close this issue.

**Comment by ropalka** [comment]
No problem we will integrate eclipse transformer into batavia project via our API.
