### ISSUE TITLE
Refactor state information used by the transformer and by actions

### ISSUE THREAD

**Issue by tbitonti** [eclipse/transformer#83]
The current action framework is stateless, which is desirable for reusing the same action objects in the action hierarchy, but is a problem for managing state when invoking actions.

This update is to introduce a single "TransformerState" object which will encapsulate the current transformer state and which will be provided to actions as a way of associating state more cleanly.

[TransformerState.java.txt](https://github.com/eclipse/transformer/files/4854599/TransformerState.java.txt)

**Comment by bjhargrave** [comment]
How will the state object be known to other objects? Will all the method signatures be updated to pass the state object down the call chain? Or will the state object be in some well known place?

**Comment by tbitonti** [comment]
The action API is updated to pass in the state reference:
apply(TransformerState, String, File, File)
apply(TransformerState, String, InputStream, int)
apply(TransformerState, String, InputStream, long, OutputStream)
apply(TransformerState, String, InputStream)
Alternatively, since the state object doesn't change, the state reference could be passed in to the actions when they are created.  That would work for command line transformation, but not for other cases.

The intent is to get ahead of code such as the following:

https://github.com/eclipse/transformer/pull/76

```
96 ...clipse.transformer/src/main/java/org/eclipse/transformer/action/impl/ClassActionImpl.java 

@@ -377,7 +377,7 @@ public ByteData apply(String inputName, byte[] inputBytes, int inputLength) thro
		}
		while (fields.hasNext()) {
			FieldInfo inputField = fields.next();
-			FieldInfo outputField = transform(inputField, FieldInfo::new, SignatureType.FIELD);
+			FieldInfo outputField = transform(inputField, FieldInfo::new, SignatureType.FIELD, inputName);
```
'inputName' is just one part of state.
